package com.rhmauricio.proyectopdi.constants;

public class Constants {
    //key for login generated by AWS
    public final static String COGNITO_IDENTITY_POOL = "us-east-2:2bc29928-e669-49a9-9725-c5717663fbc7";
    public final static int CINECOLOMBIA=0;
    public final static int COLOMBIA=1;
    public final static int CREPES=2;
    public final static int SURAA=3;

}
